name: Build and Test
on:
  workflow_dispatch:
  push:
    branches:
    - master
    - fix-*
    - feat-*
    - update-*
    paths:
    - '**.go'
    - go.mod
    - go.sum
  pull_request:
    paths:
    - '**.go'
    - go.mod
    - go.sum
    types:
    - opened
    - synchronize
    - reopened
jobs:
  build-test-publish_coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - run: go build
    - run: go test -coverprofile='coverage.out'
    - uses: sonarsource/sonarqube-scan-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=wranders
          -Dsonar.projectKey=wranders_coredns-filter
          -Dsonar.go.coverage.reportPaths=coverage.out
          -Dsonar.verbose=true
          -Dsonar.sources=.
          -Dsonar.exclusions=**/*_test.go,.testdata/*
          -Dsonar.tests=.
          -Dsonar.test.inclusions=**/*_test.go
