name: Release
on:
  push:
    tags:
    - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
    - run: git tag -l --format='%(contents:subject)%0a%0a%(contents:body)' > RELEASE.txt
    - uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body_path: RELEASE.txt
